version: "3"

services:
  php:
    container_name: ${PROJECT_NAME}-php
    image: ${PROJECT_NAME}/php:${PHP_VERSION}
    volumes:
      - ~/.composer-docker/cache:/var/www/.composer/cache
      - ./:/app
      - ./docker/php/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint:ro
      - ./docker/php/.bashrc:/var/www/.bashrc
    environment:
      PHP_USER_ID: ${PHP_USER_ID}
      COMPOSER_MEMORY_LIMIT: -1
    restart: ${RESTART}
    depends_on:
      - db

  nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:1.27.1-alpine3.20
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    restart: ${RESTART}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:${DOCKER_DOMAIN},${ADMIN_DOMAIN}"
    networks:
      - default
      - web
    depends_on:
      - php

  db:
    container_name: ${PROJECT_NAME}-db
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${DOCKER_DB_PORT}:5432
    restart: ${RESTART}

  node:
    container_name: ${PROJECT_NAME}-node
    image: node:22.9.0-alpine3.20
    user: "node"
    working_dir: /app
    volumes:
      - ./:/app:delegated
    command: /bin/true

  php-cron:
    container_name: ${PROJECT_NAME}-cron
    image: ${PROJECT_NAME}-cron/php:${PHP_VERSION}
    volumes:
      - ./:/app
      - ./docker/php/.bashrc:/var/www/.bashrc
      - ./docker/php-cron/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint:ro
      - ./docker/php-cron/schedule:/etc/cron.d/schedule:ro
    environment:
      PHP_USER_ID: ${PHP_USER_ID}
    restart: ${RESTART}
    command: cron -f
    depends_on:
      - php

  php-worker:
    container_name: ${PROJECT_NAME}-worker
    image: ${PROJECT_NAME}/php:${PHP_VERSION}
    volumes:
      - ~/.composer-docker/cache:/var/www/.composer/cache
      - ./:/app
      - ./docker/php/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint:ro
      - ./docker/php/.bashrc:/var/www/.bashrc
    environment:
      PHP_USER_ID: ${PHP_USER_ID}
      COMPOSER_MEMORY_LIMIT: -1
    restart: ${RESTART}
    command: su -l www-data -s /bin/bash -c '/usr/local/bin/php /app/artisan queue:work --queue=high,default'
    depends_on:
      - php

  mailcatcher:
    container_name: ${PROJECT_NAME}-mailcatcher
    image: jeanberu/mailcatcher:latest
    labels:
      traefik.enable: "true"
      traefik.port: "1080"
      traefik.frontend.rule: "Host:mail.${DOCKER_DOMAIN}"
    networks:
      - default
      - web
    command: "mailcatcher --no-quit --foreground --ip=0.0.0.0 --smtp-port=${MAIL_PORT}"
    restart: ${RESTART}

volumes:
  db_data:

networks:
  web:
    external: true
