#!/bin/sh
set -e

crontab /etc/cron.d/schedule

usermod -u ${PHP_USER_ID} www-data

export PS1="\e[0;35mphd \e[0;37m\u container \h \e[0;32m\w \e[0;0m\n$ "

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    if [ -x "$(command -v apache2-foreground)" ]; then
        set -- apache2-foreground "$@"
    elif [ -x "$(command -v php-fpm)" ]; then
        set -- php-fpm "$@"
    else
        set -- php "$@"
    fi
fi

exec "$@"
